
// Define a simple set of question-answer pairs
const responses = {
  "hello": "Hi there! How can I help you?",
  "how are you": "How you doing?",
  "1": "To know there is a God",
  "2": "Not to entertain thoughts of other gods besides Him",
  "3": "To unify God",
  "4": "To love God",
  "5": "To fear God",
  "6": "To sanctify God's Name",
  "7": "Not to profane God's Name",
  "8": "Not to destroy objects associated with God's Name",
  "9": "To listen to the prophet speaking in His Name",
  "10": "To remember the exodus from Egypt",
  "11": "To observe the Sabbath",
  "12": "To honor the Sabbath",
  "13": "Not to leave the boundaries of your city on the Sabbath",
  "14": "To sanctify the new month",
  "15": "To slaughter the Passover offering",
  "16": "To eat the Passover offering",
  "17": "Not to eat the Passover offering raw or boiled",
  "18": "Not to leave any meat from the Passover offering over until morning",
  "19": "Not to break any bones from the Passover offering",
  "20": "Not to take the Passover offering out of the group",
  "21": "To celebrate the festival of Shavuot",
  "22": "Not to do work on the first day of Shavuot",
  "23": "To bring a new meal offering on Shavuot",
  "24": "To celebrate the festival of Sukkot for seven days",
  "25": "Not to do work on the first day of Sukkot",
  "26": "To take up a Lulav and Etrog on the first day",
  "27": "To dwell in a Sukkah for seven days",
  "28": "To celebrate the festival of Rosh Hashanah",
  "29": "Not to do work on Rosh Hashanah",
  "30": "To hear the sound of the shofar on Rosh Hashanah",
  "31": "To fast on Yom Kippur",
  "32": "Not to do work on Yom Kippur",
  "33": "To confess sins on Yom Kippur",
  "34": "To repent from sin",
  "35": "To confess sins",
  "36": "Not to eat or drink on Yom Kippur",
  "37": "To celebrate the festival of Passover",
  "38": "Not to do work on the first day of Passover",
  "39": "Not to eat leaven on Passover",
  "40": "Not to eat mixtures containing leaven on Passover",
  "41": "Not to see leaven during Passover",
  "42": "Not to find leaven in your possession during Passover",
  "43": "To destroy all leaven before Passover",
  "44": "To relate the exodus from Egypt on that night",
  "45": "To eat matzah on the first night of Passover",
  "46": "Not to eat anything after the Passover lamb",
  "47": "Not to work on the intermediate days of Passover and Sukkot when it is not necessary",
  "48": "Not to work on the seventh day of Passover",
  "49": "To count forty-nine days from the time of the cutting of the Omer",
  "50": "To bring the Two Loaves to the Temple on Shavuot",
  "51": "To offer a sacrifice of well-being and to chant the Hallel on festivals",
  "52": "To rejoice on the festivals",
  "53": "To give gifts to the poor on the festivals",
  "54": "To assemble all Israelites on the Sukkot following the seventh year",
  "55": "To appear before the Lord during the festivals",
  "56": "Not to appear before the Lord without offerings",
  "57": "To bring all free-will offerings on the first subsequent festival",
  "58": "To decree a leap year",
  "59": "Not to break vows",
  "60": "To swear by His Name truthfully",
  "61": "Not to delay fulfilling vows",
  "62": "Not to break oaths",
  "63": "Not to test the prophet unduly",
  "64": "The court must execute by the sword",
  "65": "To appoint judges",
  "66": "To fear the court",
  "67": "Not to curse judges",
  "68": "Not to curse the head of state or leader",
  "69": "Not to curse any upstanding Jew",
  "70": "To pay a worker on the day the work was done",
  "71": "Not to withhold wages overnight",
  "72": "The hired worker may eat of the unharvested crops where he works",
  "73": "The hired worker may not take more than he can eat",
  "74": "Not to muzzle an ox while it is threshing",
  "75": "To give charity",
  "76": "Not to refrain from maintaining a poor man and giving him what he needs",
  "77": "To give a Hebrew servant gifts when he goes free",
  "78": "Not to send him away empty-handed",
  "79": "To lend to the poor and destitute",
  "80": "Not to press them for repayment if you know they don't have it",
  "81": "Not to refuse a loan to a poor man when you have the means",
  "82": "To release all loans during the Shemittah year",
  "83": "To exact the debts of an alien",
  "84": "Not to exact the debts of an Israelite",
  "85": "To give tithes to the poor (Maaser Ani) every third and sixth year",
  "86": "To read the confession of tithes every fourth and seventh year",
  "87": "To rest the land during the seventh year by not doing any work which enhances growth",
  "88": "Not to work the land during the seventh year",
  "89": "Not to harvest a crop normally as if it were your own in the seventh year",
  "90": "Not to gather the grapes which grow wild in the seventh year, as if it were your own vintage",
  "91": "To leave the produce of the land in the seventh year for the poor and for animals", 
  "92": "To release all Hebrew servants in the Jubilee year", 
  "93": "Not to work the land in the Jubilee year",
  "94": "Not to reap in the Jubilee year as in other years", 
  "95": "Not to gather the fruit in the Jubilee year as in other years", 
  "96": "To count the years to the Jubilee",
  "97": "To blow the shofar on Yom Kippur of the Jubilee year",
  "98": "To sanctify the fiftieth year",
  "99": "Not to sell the land permanently",
  "100": "To redeem the land that has been sold",
  "101": "Not to sell the land in Israel indefinitely",
  "102": "To grant redemption for houses in walled cities within a year",
  "103": "To redeem a Levite’s house in a walled city",
  "104": "Not to sell the field of the Levites",
  "105": "To give the Levites cities to dwell in and their surrounding fields",
  "106": "Not to change the boundaries of the Levites’ cities",
  "107": "Not to plant diverse seeds together",
  "108": "Not to crossbreed animals of different species",
  "109": "Not to work different kinds of animals together",
  "110": "Not to wear a garment made of wool and linen mixed together (Shaatnez)",
  "111": "Not to sow grain or vegetables in a vineyard",
  "112": "Not to eat fruit from a tree during its first three years (Orlah)",
  "113": "Not to eat diverse seeds planted in a vineyard",
  "114": "To sanctify the first fruits and bring them to the Temple",
  "115": "To recite the declaration upon bringing first fruits",
  "116": "To separate tithes from agricultural produce",
  "117": "To separate the First Tithe for the Levites",
  "118": "To separate the Second Tithe and eat it in Jerusalem",
  "119": "Not to consume the Second Tithe outside of Jerusalem",
  "120": "To redeem the Second Tithe if unable to bring it to Jerusalem",
  "121": "To give the Priests their due portions (Terumah)",
  "122": "To separate the Challah portion for the Kohen",
  "123": "Not to eat the Terumah while in a state of impurity",
  "124": "Not to eat unredeemed Second Tithe grain",
  "125": "Not to eat unredeemed Firstborn animal offerings",
  "126": "To bring the Firstborn of clean animals to the Temple",
  "127": "To redeem the firstborn son",
  "128": "To redeem a firstborn donkey",
  "129": "To break the neck of a firstborn donkey if it is not redeemed",
  "130": "Not to redeem the Firstborn of clean animals",
  "131": "To bring the offerings due from cattle and sheep",
  "132": "Not to delay the bringing of vows and offerings",
  "133": "To offer all sacrifices in the Temple",
  "134": "Not to slaughter sacrifices outside the Temple courtyard", 
  "135": "Not to eat sacrifices outside the designated area", 
  "136": "To bring all offerings to the Temple from outside Israel", 
  "137": "To treat the remains of sacrificial animals properly",
  "138": "Not to eat an offering that has become impure", 
  "139": "To burn the leftovers of offerings", 
  "140": "To eat peace offerings within the prescribed time",
  "141": "Not to eat from sacrifices beyond the permitted time", 
  "142": "Not to eat sacrifices that are disqualified", 
  "143": "To burn disqualified sacrifices",
  "144": "To bring all required offerings on the festivals", 
  "145": "To bring the Chagigah offering on the festivals",
  "146": "Not to eat Chametz (leavened bread) on Pesach",
  "147": "Not to possess Chametz on Pesach", 
  "148": "To destroy all Chametz before Pesach", 
  "149": "To eat Matzah on the first night of Pesach",
  "150": "To rest on the first day of Pesach", 
  "151": "To rest on the seventh day of Pesach", 
  "152": "To count the Omer for seven weeks",
  "153": "To rest on Shavuot", 
  "154": "To rest on Rosh Hashanah",
  "155": "To hear the Shofar on Rosh Hashanah",
  "156": "To rest on Yom Kippur", 
  "157": "To fast on Yom Kippur",
  "158": "To rest on the first day of Sukkot",
  "159": "To rest on Shemini Atzeret", 
  "160": "To dwell in a Sukkah during Sukkot",
  "161": "To take the Four Species (Lulav, Etrog, Hadassim, and Aravot) on Sukkot",
  "162": "Not to work on Shabbat", 
  "163": "To rest on Shabbat", 
  "164": "Not to light a fire on Shabbat", 
  "165": "Not to carry in a public domain on Shabbat",
  "166": "To sanctify the Shabbat day", 
  "167": "To honor one's father and mother", 
  "168": "Not to curse one’s parents", 
  "169": "Not to strike one's parents",
  "170": "Not to rebel against the Sanhedrin", 
  "171": "To appoint a king",
  "172": "Not to curse the king",
  "173": "Not to curse a judge",
  "174": "Not to testify falsely", 
  "175": "Not to testify on hearsay",
  "176": "Not to take a bribe", 
  "177": "Not to pervert justice", 
  "178": "To set aside cities of refuge for accidental killers",
  "179": "Not to take ransom for a murderer", 
  "180": "Not to oppress the stranger", 
  "181": "To love the stranger", 
  "182": "Not to mistreat widows and orphans",
  "183": "Not to lend with interest to a fellow Jew", 
  "184": "To return lost objects", 
  "185": "Not to ignore a lost object", 
  "186": "Not to hate a fellow Jew in your heart",
  "187": "To rebuke a fellow Jew when necessary",
  "188": "Not to take revenge",
  "189": "Not to bear a grudge", 
  "190": "To love your fellow Jew as yourself",
  "191": "Not to mistreat a hired worker",
  "192": "To pay a hired worker on time",
  "193": "Not to withhold wages", 
  "194": "Not to cheat in measures and weights", 
  "195": "To have honest scales and measures",
  "196": "Not to move boundary markers", 
  "197": "Not to wrong one another in business",
  "198": "Not to kidnap a fellow Jew",
  "199": "Not to withhold food, clothing, or marital rights from a wife",
  "200": "Not to mistreat a debtor",
  "201": "Not to charge interest on loans to a fellow Jew",
  "202": "To lend to a fellow Jew in need",
  "203": "Not to take security for a loan in an unfair manner",
  "204": "To return a security to a debtor when needed",
  "205": "Not to delay the wages of a hired worker",
  "206": "To release a Hebrew servant after six years",
  "207": "Not to send away a freed servant empty-handed",
  "208": "To give a freed Hebrew servant gifts",
  "209": "Not to sell a Hebrew servant as a slave",
  "210": "Not to work a Hebrew servant with rigorous labor",
  "211": "Not to allow a Hebrew servant to remain a slave permanently",
  "212": "To redeem a Hebrew maidservant",
  "213": "Not to sell a Hebrew maidservant to another",
  "214": "To allow a Hebrew maidservant to be freed upon reaching maturity",
  "215": "Not to mistreat a stranger",
  "216": "Not to oppress a stranger",
  "217": "Not to pervert justice for the orphan or widow",
  "218": "Not to wrong one another in business",
  "219": "To have honest scales and measures",
  "220": "Not to move boundary markers",
  "221": "Not to curse a deaf person",
  "222": "Not to put a stumbling block before the blind",
  "223": "Not to gossip",
  "224": "Not to bear false witness",
  "225": "Not to withhold testimony",
  "226": "Not to curse a judge",
  "227": "Not to curse a leader of the people",
  "228": "Not to curse a fellow Jew",
  "229": "Not to strike a fellow Jew",
  "230": "Not to murder",
  "231": "Not to accept ransom for a murderer",
  "232": "To designate cities of refuge for accidental killers",
  "233": "Not to kill the murderer before trial",
  "234": "Not to spare a murderer from justice",
  "235": "Not to stand idly by when a fellow Jew's life is in danger",
  "236": "Not to mistreat a captive woman",
  "237": "To provide for the needs of a captive woman",
  "238": "Not to sell a captive woman into slavery",
  "239": "To fulfill the laws of the war bride",
  "240": "Not to destroy fruit trees during a siege",
  "241": "To offer peace before attacking a city",
  "242": "Not to break a vow or swear falsely",
  "243": "Not to take God's name in vain",
  "244": "To sanctify God's name",
  "245": "Not to desecrate God's name",
  "246": "To love God",
  "247": "To fear God",
  "248": "To walk in God's ways",
  "249": "To cleave to God",
  "250": "To swear by God's name in truth",
  "251": "Not to follow the ways of idolaters",
  "252": "Not to turn to idol worship",
  "253": "Not to make an idol",
  "254": "Not to bow down to an idol",
  "255": "Not to worship idols",
  "256": "Not to sacrifice to idols",
  "257": "Not to make a graven image",
  "258": "Not to make figures of angels or celestial beings",
  "259": "Not to turn others towards idol worship",
  "260": "Not to listen to one who entices others to idolatry",
  "261": "Not to love an idolater who entices others",
  "262": "Not to cease hating an idolater who entices others",
  "263": "Not to save an idolater who entices others",
  "264": "Not to defend an idolater who entices others",
  "265": "Not to refrain from incriminating an idolater who entices others",
  "266": "Not to rebuild a destroyed city that was turned to idolatry",
  "267": "Not to benefit from anything from an idolatrous city",
  "268": "To burn an idolatrous city and its possessions",
  "269": "Not to rebuild a destroyed idolatrous city",
  "270": "Not to use anything from an idolatrous city",
  "271": "Not to cut oneself for the dead",
  "272": "Not to shave the front of the head for the dead",
  "273": "Not to tattoo oneself",
  "274": "Not to wear garments made of Shaatnez (wool and linen)",
  "275": "Not to round the corners of one's head",
  "276": "Not to destroy the beard",
  "277": "Not to eat meat from an animal that was not slaughtered properly",
  "278": "Not to eat blood",
  "279": "Not to eat the fat of kosher animals",
  "280": "Not to eat a limb torn from a living animal",
  "281": "Not to eat the sciatic nerve",
  "282": "Not to eat non-kosher fish",
  "283": "Not to eat non-kosher flying insects",
  "284": "Not to eat creeping creatures",
  "285": "Not to eat swarming creatures",
  "286": "Not to eat meat and milk cooked together",
  "287": "Not to cook meat and milk together",
  "288": "Not to benefit from meat and milk cooked together",
  "289": "Not to eat bread from new grain before the Omer offering",
  "290": "Not to eat parched grain from new grain before the Omer offering",
  "291": "Not to eat fresh grain from new grain before the Omer offering",
  "292": "To remove all Chametz before Pesach",
  "293": "Not to own Chametz during Pesach",
  "294": "Not to eat Chametz after midday on Erev Pesach",
  "295": "To eat Matzah on the first night of Pesach",
  "296": "Not to eat Chametz during Pesach",
  "297": "Not to benefit from Chametz during Pesach",
  "298": "Not to eat leavened dough offerings",
  "299": "Not to eat sacrifices that have become impure",
  "300": "Not to leave parts of sacrifices overnight",
  "301": "Not to plant a tree in the Temple courtyard",
"302": "Not to build a stone pillar for worship",
"303": "Not to make an idol or graven image",
"304": "Not to turn a city to idolatry",
"305": "Not to derive benefit from an idolatrous city",
"306": "To burn an idolatrous city and all its contents",
"307": "Not to rebuild an idolatrous city",
"308": "Not to listen to a false prophet",
"309": "Not to prophesy falsely in God's Name",
"310": "Not to fear killing a false prophet",
"311": "Not to swear falsely in God's Name",
"312": "Not to take God's Name in vain",
"313": "Not to curse God",
"314": "Not to curse a ruler or judge",
"315": "Not to curse a fellow Jew",
"316": "Not to curse one's parents",
"317": "Not to strike one's parents",
"318": "Not to rebel against a priest or judge",
"319": "Not to add to the Torah commandments",
"320": "Not to diminish from the Torah commandments",
"321": "To heed the decisions of the Sanhedrin",
"322": "Not to follow the majority to do evil",
"323": "Not to pervert justice",
"324": "Not to favor a guilty person in judgment",
"325": "Not to accept bribes",
"326": "Not to delay judgment",
"327": "Not to appoint an unqualified judge",
"328": "Not to bear false witness",
"329": "Not to accept false testimony",
"330": "To interrogate witnesses thoroughly",
"331": "Not to judge based on circumstantial evidence alone",
"332": "Not to convict on a single witness's testimony",
"333": "Not to execute judgment in capital cases without a majority",
"334": "Not to pity a murderer",
"335": "Not to take ransom for a murderer",
"336": "Not to kill an innocent person",
"337": "Not to leave a murderer unpunished",
"338": "Not to spare a pursuer who intends to kill",
"339": "To establish cities of refuge",
"340": "Not to kill a refugee before trial",
"341": "Not to move a landmark",
"342": "Not to steal",
"343": "Not to rob",
"344": "Not to covet another's possessions",
"345": "Not to desire another’s house, wife, or property",
"346": "Not to kidnap a person",
"347": "Not to withhold wages from a worker",
"348": "To pay workers on time",
"349": "Not to delay payment of wages",
"350": "Not to oppress the poor or destitute",
"351": "Not to lend with interest to a fellow Jew",
"352": "Not to borrow with interest from a fellow Jew",
"353": "Not to demand repayment of a loan during the Sabbatical year",
"354": "Not to deny money owed",
"355": "Not to take a pledge from a debtor forcefully",
"356": "To return a pledge to a poor debtor before sunset",
"357": "Not to take a widow’s garment as a pledge",
"358": "Not to pervert justice for the stranger or orphan",
"359": "Not to muzzle an ox while it threshes",
"360": "Not to plant different species together",
"361": "Not to plow with an ox and a donkey together",
"362": "Not to wear wool and linen together (Shatnez)",
"363": "Not to crossbreed different species of animals",
"364": "Not to eat the fruit of a tree in its first three years",
"365": "To set aside a portion of the harvest for the poor",
"366": "To leave the corners of the field for the poor",
"367": "To leave fallen sheaves for the poor",
"368": "Not to gather the forgotten sheaf",
"369": "To leave grape gleanings for the poor",
"370": "Not to gather small clusters of grapes",
"371": "Not to return to take a forgotten bundle",
"372": "To lend to the poor",
"373": "Not to turn away a needy person",
"374": "Not to lend at interest to a fellow Jew",
"375": "Not to take interest from a Jew",
"376": "Not to deceive in weights and measures",
"377": "To use accurate weights and measures",
"378": "Not to curse the deaf",
"379": "Not to place a stumbling block before the blind",
"380": "To rebuke one's fellow Jew when necessary",
"381": "Not to hate a fellow Jew in one’s heart",
"382": "Not to take revenge",
"383": "Not to bear a grudge",
"384": "To love one’s fellow as oneself",
"385": "Not to stand idly by when another is in danger",
"386": "Not to defraud or oppress a fellow Jew",
"387": "Not to defraud or oppress a stranger",
"388": "Not to wrong a convert with words",
"389": "To love the convert",
"390": "Not to harm a widow or orphan",
"391": "Not to insult or shame a fellow Jew",
"392": "Not to speak gossip (Lashon Hara)",
"393": "Not to spread false rumors",
"394": "Not to testify falsely",
"395": "Not to slander a fellow Jew",
"396": "Not to hold a grudge against others",
"397": "Not to shame someone in public",
"398": "To correct others with love and respect",
"399": "Not to embarrass someone needlessly",
"400": "To help unload a burdened animal"


  "help": "I can only answer a few questions. Try saying hello, or ask how I am."
};

const defaultResponse = "I'm sorry, I don't understand that.";

// Grab elements from the DOM
const chatbox = document.getElementById("chatbox");
const userInput = document.getElementById("userInput");
const sendBtn = document.getElementById("sendBtn");

// Function to add a message to the chatbox
function addMessage(message, sender) {
  const messageElem = document.createElement("div");
  messageElem.className = sender === "user" ? "userMessage" : "botMessage";
  messageElem.textContent = message;
  chatbox.appendChild(messageElem);
  // Keep chatbox scrolled to the bottom
  chatbox.scrollTop = chatbox.scrollHeight;
}

// Main function to handle user input
function handleInput() {
  const text = userInput.value.trim().toLowerCase();
  if (text.length === 0) return;
  
  // Display user message
  addMessage(text, "user");
  
  // Check if user input matches a known question
  let reply = defaultResponse;
  if (responses[text]) {
    reply = responses[text];
  }
  
  // Display bot response
  addMessage(reply, "bot");
  
  // Clear the input
  userInput.value = "";
}

// Event listeners
sendBtn.addEventListener("click", handleInput);
userInput.addEventListener("keypress", function(e) {
  if (e.key === "Enter") {
    handleInput();
  }
});
